#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://0.0.0.0:3306/gulimall_sms
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 0.0.0.0:8848
#  application:
#    name: gulimall-coupon
#
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#server:
#  port: 7001
ribbon:
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 30000